on:
  workflow_call:
    inputs:
      buildDir:
        description: 'Maven build directory. Default is current dir.'
        required: false
        type: string
      depProperty:
        description: 'New release version to be used on this property'
        required: false
        type: string
      depDirectory:
        description: 'Directory for pom.xml containing the dependency'
        required: false
        type: string
    outputs:
      tag:
        description: "Release tag"
        value: ${{ jobs.pre-release.outputs.tag }}

jobs:
  pre-release:
    runs-on: ubuntu-latest
    # Map the job outputs to step outputs
    outputs:
      tag: ${{ steps.release.outputs.tag }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 5

      - name: Configure GIT
        run: |
          git config --global user.name 'Gluon Bot'
          git config --global user.email 'gluon-bot@users.noreply.github.com'

      - name: Setup Java and Apache Maven
        uses: actions/setup-java@v3
        with:
          distribution: 'oracle'
          java-version: '17'

      - name: Update to release version
        id: release
        run: |
          if [ -z "$BUILD_DIR" ]; then
            BUILD_DIR=.
          fi
          mvn -q versions:set -DremoveSnapshot -DgenerateBackupPoms=false -f $BUILD_DIR
          git add $BUILD_DIR/pom.xml
          PROJECT_VERSION=$(mvn -q help:evaluate -Dexpression=project.version -q -DforceStdout -f $BUILD_DIR)
          if [ ! -z "$DEP_PROPERTY" ] && [ ! -z "$DEP_DIR" ]; then
            mvn -q versions:set-property -Dproperty=$DEP_PROPERTY -DnewVersion=$PROJECT_VERSION -f $DEP_DIR
            git add $DEP_DIR/pom.xml
          fi
          git commit -m "Release v$PROJECT_VERSION"
          git push https://gluon-bot:$PAT@github.com/$GITHUB_REPOSITORY HEAD:main
          git tag $PROJECT_VERSION
          git push https://gluon-bot:$PAT@github.com/$GITHUB_REPOSITORY $PROJECT_VERSION
          echo "tag=$PROJECT_VERSION" >> $GITHUB_OUTPUT
        shell: bash
        env:
          PAT: ${{ secrets.GITHUB_TOKEN }}
          BUILD_DIR: ${{ inputs.buildDir }}
          DEP_PROPERTY: ${{ inputs.depProperty }}
          DEP_DIR: ${{ inputs.depDirectory }}
